-- Auto-generated seed from mock data
-- Run after 001_initial_schema.sql

-- apps
insert into apps (id, app_store_id, name, developer, category, icon_url, description) values
('chatgpt','6448311069','ChatGPT','OpenAI','Productivity','/app-icons/chatgpt.png','The official ChatGPT app by OpenAI.'),
('notability','360593530','Notability','Ginger Labs','Productivity','/app-icons/notability.png','Take notes, annotate PDFs, and sketch ideas.'),
('notion','1232780281','Notion','Notion Labs, Inc.','Productivity','/app-icons/notion.png','Notes, docs, wikis, tasks — all in one workspace.'),
('microsoft-365','586447913','Microsoft 365','Microsoft Corporation','Productivity','/app-icons/microsoft-365.png','Word, Excel, PowerPoint and more.'),
('grammarly','1158877342','Grammarly','Grammarly, Inc.','Productivity','/app-icons/grammarly.png','Writing assistant for grammar, spelling, and style.'),
('todoist','572688855','Todoist','Doist Inc.','Productivity','/app-icons/todoist.png','To-do list and task manager.'),
('bear','1016366447','Bear','Shiny Frog Ltd.','Productivity','/app-icons/bear.png','Beautiful markdown notes and writing app.'),
('things3','904237743','Things 3','Cultured Code GmbH','Productivity','/app-icons/things3.png','Award-winning personal task manager.'),
('fantastical','718043190','Fantastical','Flexibits Inc.','Productivity','/app-icons/fantastical.png','Calendar and tasks with natural language parsing.'),
('ulysses','1225571038','Ulysses','Ulysses GmbH & Co. KG','Productivity','/app-icons/ulysses.png','Professional writing app for authors.'),
('1password','568903335','1Password','AgileBits','Utilities','/app-icons/1password.png','The world''s most-loved password manager.'),
('day-one','1044867788','Day One','Automattic','Lifestyle','/app-icons/day-one.png','Private journal and diary app.'),
('drafts','1236254471','Drafts','Agile Tortoise','Productivity','/app-icons/drafts.png','Where text starts. Quick capture and action.'),
('obsidian','1557175442','Obsidian','Dynalist Inc.','Productivity','/app-icons/obsidian.png','A powerful knowledge base on your local device.'),
('readwise-reader','1567599761','Readwise Reader','Readwise','Productivity','/app-icons/readwise-reader.png','The reading app for the modern age.'),
('craft','1487937127','Craft','Luki Lab Kft.','Productivity','/app-icons/craft.png','A new take on documents for Apple devices.'),
('spotify','324684580','Spotify','Spotify AB','Music','/app-icons/spotify.png','Enjoy music, podcasts, and more.'),
('tidal','913943275','Tidal','Tidal Music AS','Music','/app-icons/tidal.png','Hi-fi music streaming with exclusive content.'),
('deezer','292738169','Deezer','Deezer SA','Music','/app-icons/deezer.png','Stream over 120 million songs.'),
('overcast','888422857','Overcast','Overcast Radio, LLC','Entertainment','/app-icons/overcast.png','The best podcast app for iPhone.'),
('pocket-casts','414834813','Pocket Casts','Pocket Casts','Entertainment','/app-icons/pocket-casts.png','Listen to podcasts, ad-free.'),
('procreate','364519085','Procreate','Savage Interactive','Design','/app-icons/procreate.png','The most powerful illustration and painting app.'),
('canva','897446215','Canva','Canva','Design','/app-icons/canva.png','Design anything. Publish anywhere.'),
('pixelmator-pro','1289583905','Pixelmator Pro','UAB Pixelmator Team','Design','/app-icons/pixelmator-pro.png','Powerful image editor for Mac and iPad.'),
('linea-link','1274697134','Linea Link','The Iconfactory','Design','/app-icons/linea-link.png','Simple, distraction-free drawing app for iPad.'),
('affinity-photo','1239901859','Affinity Photo 2','Serif Labs','Photo & Video','/app-placeholder.svg','Professional photo editing and retouching.'),
('affinity-designer','1274090551','Affinity Designer 2','Serif Labs','Design','/app-placeholder.svg','Professional vector graphic design.'),
('facetune','1149994032','Facetune','Lightricks','Photo & Video','/app-icons/facetune.png','Professional photo editing for portraits.'),
('adobe-lightroom','878783582','Adobe Lightroom','Adobe Inc.','Photo & Video','/app-icons/adobe-lightroom.png','Professional photo editing and organization.'),
('vsco','588013838','VSCO','Visual Supply Company','Photo & Video','/app-icons/vsco.png','Photo editor and creative community.'),
('darkroom','953286746','Darkroom','Gallery Technologies Inc.','Photo & Video','/app-icons/darkroom.png','Fast photo and video editing.'),
('halide','885697368','Halide Mark II','Lux Optics Inc.','Photo & Video','/app-icons/halide.png','Professional RAW camera app.'),
('luma-ai','1631331986','Luma AI','Luma AI Inc.','Photo & Video','/app-icons/luma-ai.png','AI-powered 3D capture and video generation.'),
('capcut','1500855883','CapCut','Bytedance Pte. Ltd','Photo & Video','/app-icons/capcut.png','All-in-one video editor and maker.'),
('netflix','363590051','Netflix','Netflix, Inc.','Entertainment','/app-icons/netflix.png','Watch TV shows and movies anytime.'),
('youtube-premium','544007664','YouTube Premium','Google LLC','Entertainment','/app-icons/youtube-premium.png','Ad-free YouTube with background play.'),
('disney-plus','1446075923','Disney+','Disney','Entertainment','/app-icons/disney-plus.png','Disney, Pixar, Marvel, Star Wars & more.'),
('hbo-max','1666653815','Max','Warner Bros.','Entertainment','/app-icons/hbo-max.png','Stream HBO, Warner Bros., DC, and more.'),
('amazon-prime','545519333','Amazon Prime Video','AMZN Mobile LLC','Entertainment','/app-icons/amazon-prime.png','Watch movies & TV series on Prime Video.'),
('apple-tv','1174078549','Apple TV+','Apple','Entertainment','/app-icons/apple-tv.png','Original shows and movies from Apple.'),
('headspace','493145008','Headspace','Headspace Inc.','Health & Fitness','/app-icons/headspace.png','Meditation and mindfulness for any mind.'),
('calm','571800810','Calm','Calm.com, Inc.','Health & Fitness','/app-icons/calm.png','Sleep, meditate, relax.'),
('strava','426826109','Strava','Strava Inc.','Health & Fitness','/app-icons/strava.png','Running and cycling GPS tracker.'),
('noom','634598719','Noom','Noom, Inc.','Health & Fitness','/app-icons/noom.png','Weight loss and behavior change program.'),
('peloton','792750948','Peloton','Peloton Interactive, Inc.','Health & Fitness','/app-icons/peloton.png','Fitness classes at home or on the go.'),
('whoop','933944389','WHOOP','WHOOP Inc.','Health & Fitness','/app-icons/whoop.png','Advanced fitness and recovery tracker.'),
('duolingo','570060128','Duolingo','Duolingo','Education','/app-icons/duolingo.png','Learn languages for free, forever.'),
('babbel','829587759','Babbel','Lesson Nine GmbH','Education','/app-icons/babbel.png','Learn a new language effectively.'),
('masterclass','1273222932','MasterClass','Yanka Industries, Inc.','Education','/app-icons/masterclass.png','Learn from the world\''s best instructors.'),
('skillshare','916819843','Skillshare','Skillshare, Inc.','Education','/app-icons/skillshare.png','Online learning for creative and curious people.'),
('coursera','736535961','Coursera','Coursera','Education','/app-icons/coursera.png','Courses from top universities and companies.'),
('robinhood','938003185','Robinhood','Robinhood Markets, Inc.','Finance','/app-icons/robinhood.png','Invest in stocks, ETFs, and crypto.'),
('coinbase','886427730','Coinbase','Coinbase, Inc.','Finance','/app-icons/coinbase.png','Buy, sell, and manage cryptocurrency.'),
('ynab','1010865877','YNAB','You Need A Budget LLC','Finance','/app-icons/ynab.png','Budget app for getting ahead financially.'),
('personal-capital','504672168','Empower','Personal Capital Corporation','Finance','/app-icons/personal-capital.png','Personal finance, investing & wealth management.'),
('ivory','1527500834','Ivory','Tapbots','Social Networking','/app-icons/ivory.png','Mastodon client crafted by Tapbots.'),
('discord','985746746','Discord','Discord Inc.','Social Networking','/app-icons/discord.png','Chat for gaming, communities, and friends.'),
('telegram-premium','686449807','Telegram Premium','Telegram FZ-LLC','Social Networking','/app-icons/telegram-premium.png','Fast, secure messaging — premium features.'),
('proxyman','1551292695','Proxyman','Proxyman LLC','Developer Tools','/app-icons/proxyman.png','HTTP debugging proxy and network analyzer.'),
('working-copy','896694807','Working Copy','Anders Borum','Developer Tools','/app-icons/working-copy.png','The full-featured Git client for iOS.'),
('textsoap','0000000000','Toolbox for Word','Creativit- Mood Board & Vision','Utilities','/app-placeholder.svg','Templates and tools for Microsoft Word.'),
('nordvpn','905953485','NordVPN','Nord Security','Utilities','/app-icons/nordvpn.png','Fast and secure VPN service.'),
('expressvpn','886492891','ExpressVPN','Express Technologies Ltd.','Utilities','/app-icons/expressvpn.png','Private and secure VPN service.'),
('google-maps','585027354','Google Maps','Google LLC','Navigation','/app-icons/google-maps.png','Real-time GPS navigation and maps.'),
('waze','323229106','Waze','Waze Inc.','Navigation','/app-icons/waze.png','Community-based navigation app.'),
('airbnb','401626263','Airbnb','Airbnb, Inc.','Travel','/app-icons/airbnb.png','Find unique places to stay and experiences.'),
('tripit','311035142','TripIt','Concur Technologies','Travel','/app-icons/tripit.png','All your travel plans in one place.'),
('mymacros','805350532','MyFitnessPal','MyFitnessPal, Inc.','Health & Fitness','/app-icons/mymacros.png','Calorie counter and nutrition tracker.'),
('lifesum','286103128','Lifesum','Lifesum AB','Health & Fitness','/app-icons/lifesum.png','Healthy eating and diet tracker.'),
('minecraft','479516143','Minecraft','Mojang AB','Games','/app-icons/minecraft.png','The original open-world survival game.'),
('roblox','431946152','Roblox','Roblox Corporation','Games','/app-icons/roblox.png','Millions of experiences with friends.'),
('monument-valley','728293409','Monument Valley','ustwo games','Games','/app-icons/monument-valley.png','Illusory architecture and impossible geometry.'),
('alto-odyssey','1182456409','Alto''s Odyssey','Snowman','Games','/app-icons/alto-odyssey.png','A breathtaking endless runner.'),
('bloons-td6','1118115766','Bloons TD 6','Ninja Kiwi','Games','/app-icons/bloons-td6.png','Addictive tower defense game.'),
('apple-arcade','1484348179','Apple Arcade','Apple','Games','/app-icons/apple-arcade.png','Unlimited access to 200+ premium games.'),
('kindle','302584613','Kindle','AMZN Mobile LLC','Books','/app-icons/kindle.png','Read millions of eBooks on any device.'),
('audible','379693831','Audible','Audible, Inc.','Books','/app-icons/audible.png','Audiobooks and podcasts from Audible.'),
('scribd','542557212','Scribd','Scribd Inc.','Books','/app-icons/scribd.png','Books, audiobooks, and documents.'),
('midjourney','6480670969','Midjourney','Midjourney, Inc.','Design','/app-placeholder.svg','AI image generation from text prompts.'),
('perplexity','1668000334','Perplexity AI','Perplexity AI Inc.','Productivity','/app-icons/perplexity.png','AI-powered search and answer engine.'),
('copilot-ms','6504708398','Microsoft Copilot','Microsoft Corporation','Productivity','/app-icons/copilot-ms.png','Your everyday AI companion by Microsoft.'),
('claude-ai','6473753684','Claude','Anthropic','Productivity','/app-icons/claude-ai.png','Anthropic''s AI assistant.'),
('shopify','371294472','Shopify','Shopify Inc.','Business','/app-icons/shopify.png','Run your business from anywhere.'),
('dropbox','327630330','Dropbox','Dropbox','Productivity','/app-icons/dropbox.png','Cloud storage and file sharing.'),
('google-one','1451784328','Google One','Google LLC','Utilities','/app-icons/google-one.png','Upgrade your Google experience with more storage.')
on conflict (id) do update set
  app_store_id=excluded.app_store_id,
  name=excluded.name, developer=excluded.developer,
  category=excluded.category, icon_url=excluded.icon_url,
  description=excluded.description, updated_at=now();

-- Resolve any stale app_store_id duplicates introduced by bad mock data.
-- If a row with the same app_store_id already exists under a different id,
-- update it in place rather than erroring.
insert into apps (id, app_store_id, name, developer, category, icon_url, description)
select id, app_store_id, name, developer, category, icon_url, description
from apps where id = 'craft'
on conflict (app_store_id) do update set
  id=excluded.id,
  name=excluded.name, developer=excluded.developer,
  category=excluded.category, icon_url=excluded.icon_url,
  description=excluded.description, updated_at=now();

-- countries
insert into countries (code, name, currency, flag) values
('US','United States','USD','🇺🇸'),
('CN','China','CNY','🇨🇳'),
('JP','Japan','JPY','🇯🇵'),
('GB','United Kingdom','GBP','🇬🇧'),
('DE','Germany','EUR','🇩🇪'),
('FR','France','EUR','🇫🇷'),
('IN','India','INR','🇮🇳'),
('TR','Turkey','TRY','🇹🇷'),
('BR','Brazil','BRL','🇧🇷'),
('MX','Mexico','MXN','🇲🇽'),
('RU','Russia','RUB','🇷🇺'),
('AU','Australia','AUD','🇦🇺'),
('CA','Canada','CAD','🇨🇦'),
('KR','South Korea','KRW','🇰🇷'),
('SG','Singapore','SGD','🇸🇬'),
('HK','Hong Kong','HKD','🇭🇰'),
('TW','Taiwan','TWD','🇹🇼'),
('PL','Poland','PLN','🇵🇱'),
('AR','Argentina','ARS','🇦🇷'),
('EG','Egypt','EGP','🇪🇬')
on conflict (code) do update set
  name=excluded.name, currency=excluded.currency, flag=excluded.flag;

-- exchange_rates
insert into exchange_rates (currency, rate_to_usd, rate_to_cny) values
('USD',1,7.25),
('CNY',0.1379,1),
('JPY',0.0067,0.0485),
('GBP',1.27,9.21),
('EUR',1.09,7.90),
('INR',0.012,0.087),
('TRY',0.031,0.225),
('BRL',0.20,1.45),
('MXN',0.058,0.421),
('RUB',0.011,0.080),
('AUD',0.65,4.71),
('CAD',0.74,5.37),
('KRW',0.00075,0.00544),
('SGD',0.74,5.37),
('HKD',0.128,0.928),
('TWD',0.031,0.225),
('PLN',0.25,1.81),
('ARS',0.00098,0.0071),
('EGP',0.021,0.152)
on conflict (currency) do update set
  rate_to_usd=excluded.rate_to_usd, rate_to_cny=excluded.rate_to_cny, fetched_at=now();
