-- plans seed
-- Primary subscription plans for all 85 tracked apps.
-- Idempotent: safe to re-run.

insert into plans (id, app_id, name, billing_period, base_price_usd, is_default, description, features) values
('chatgpt-free','chatgpt','ChatGPT Free','free',0,false,'Basic GPT-4o access with limits','{"GPT-4o (limited)","Web browsing"}'),
('chatgpt-plus','chatgpt','ChatGPT Plus','monthly',20,true,'Full GPT-4o, DALL-E, advanced features','{"GPT-4o unlimited","DALL-E 3","Advanced data analysis","Custom GPTs"}'),
('claude-ai-free','claude-ai','Claude Free','free',0,false,'Limited Claude 3.5 Sonnet access','{"Claude 3.5 Sonnet (limited)"}'),
('claude-ai-pro','claude-ai','Claude Pro','monthly',20,true,'Priority access to all Claude models','{"Claude 3.5 Sonnet unlimited","Claude 3 Opus","Priority access"}'),
('perplexity-free','perplexity','Perplexity Free','free',0,false,'Basic AI search','{"Standard search","5 Pro searches/day"}'),
('perplexity-pro','perplexity','Perplexity Pro','monthly',20,true,'Unlimited Pro searches with advanced AI','{"Unlimited Pro searches","GPT-4o / Claude","Image upload"}'),
('copilot-ms-free','copilot-ms','Copilot Free','free',0,false,'Basic Copilot access','{"GPT-4 Turbo (limited)"}'),
('copilot-ms-pro','copilot-ms','Copilot Pro','monthly',20,true,'Priority access + Microsoft 365 integration','{"Priority GPT-4 Turbo","Microsoft 365 AI","Image generation"}'),
('midjourney-basic','midjourney','Midjourney Basic','monthly',10,false,'3.3 hrs fast GPU/month','{"200 image generations","3.3 hrs fast GPU"}'),
('midjourney-standard','midjourney','Midjourney Standard','monthly',30,true,'15 hrs fast GPU + unlimited relax','{"Unlimited relax mode","15 hrs fast GPU","General commercial use"}'),
('spotify-free','spotify','Spotify Free','free',0,false,'Ad-supported streaming','{"Ad-supported","Shuffle only mobile"}'),
('spotify-individual','spotify','Spotify Premium','monthly',11.99,true,'Ad-free streaming, offline, HQ','{"Ad-free","Offline downloads","High quality audio"}'),
('spotify-duo','spotify','Spotify Duo','monthly',16.99,false,'2 accounts sharing','{"2 Premium accounts","Duo Mix playlist"}'),
('spotify-family','spotify','Spotify Family','monthly',19.99,false,'Up to 6 accounts','{"6 Premium accounts","Family Mix","Content filter"}'),
('tidal-free','tidal','Tidal Free','free',0,false,'Ad-supported','{"Ad-supported","Limited skips"}'),
('tidal-individual','tidal','Tidal HiFi','monthly',11,true,'Lossless + Dolby Atmos','{"Lossless HiFi","Dolby Atmos","Offline"}'),
('deezer-free','deezer','Deezer Free','free',0,false,'Ad-supported','{"Ad-supported"}'),
('deezer-individual','deezer','Deezer Premium','monthly',11.99,true,'Ad-free, offline, HiFi','{"Ad-free","Offline","HiFi option"}'),
('overcast-free','overcast','Overcast Free','free',0,false,'Basic podcast app','{"Smart Speed","Voice Boost"}'),
('overcast-premium','overcast','Overcast Premium','monthly',9.99,true,'Unlock all features + support development','{"All features","Upload custom audio","No ads"}'),
('pocket-casts-free','pocket-casts','Pocket Casts Free','free',0,false,'Core podcast features','{"Variable speed","Trim silence"}'),
('pocket-casts-plus','pocket-casts','Pocket Casts Plus','monthly',3.99,true,'Desktop app, extra themes, folders','{"Desktop app","Watch app","Cloud storage","Themes"}'),
('notion-free','notion','Notion Free','free',0,false,'Personal use basics','{"Unlimited pages","Basic sharing"}'),
('notion-plus','notion','Notion Plus','monthly',12,true,'Unlimited guests, full version history','{"Unlimited guests","Full history","Custom domains"}'),
('notability-free','notability','Notability Free','free',0,false,'Basic notes','{"Note taking","PDF annotation"}'),
('notability-plus','notability','Notability+','annual',14.99,true,'All features including templates and cloud','{"Auto-backup","Handwriting recognition","All templates"}'),
('microsoft-365-personal','microsoft-365','Microsoft 365 Personal','monthly',9.99,true,'For 1 person — Word, Excel, PowerPoint + 1TB OneDrive','{"Word / Excel / PowerPoint","1 TB OneDrive","1 person"}'),
('microsoft-365-family','microsoft-365','Microsoft 365 Family','monthly',12.99,false,'Up to 6 people','{"Up to 6 people","6 TB OneDrive","Premium features"}'),
('grammarly-free','grammarly','Grammarly Free','free',0,false,'Basic grammar and spelling','{"Grammar check","Spelling","Punctuation"}'),
('grammarly-premium','grammarly','Grammarly Premium','monthly',30,true,'Advanced suggestions + plagiarism detection','{"Style improvements","Tone detection","Plagiarism checker"}'),
('todoist-free','todoist','Todoist Free','free',0,false,'Core task management','{"5 active projects","Collaborators"}'),
('todoist-pro','todoist','Todoist Pro','monthly',5,true,'Advanced reminders, labels, filters','{"Unlimited projects","Reminders","Labels","Activity history"}'),
('bear-free','bear','Bear Free','free',0,false,'Single device notes','{"Core editor","Tags"}'),
('bear-pro','bear','Bear Pro','monthly',3.99,true,'Sync, export, themes','{"iCloud sync","PDF/Word export","Themes"}'),
('things3-standard','things3','Things 3','one_time',9.99,true,'One-time purchase — iPhone app','{"Full GTD","Projects","Areas","Magic Plus"}'),
('fantastical-free','fantastical','Fantastical Free','free',0,false,'Basic calendar','{"Calendar views","Natural language"}'),
('fantastical-premium','fantastical','Fantastical Premium','monthly',6.75,true,'Full features incl. tasks and meet scheduling','{"Tasks","Weather","Meet with Fantastical","Widgets"}'),
('ulysses-subscription','ulysses','Ulysses','monthly',6.99,true,'Full Ulysses subscription','{"Unlimited documents","iCloud sync","Publishing","Export themes"}'),
('drafts-free','drafts','Drafts Free','free',0,false,'Core capture and editing','{"Unlimited drafts","Basic actions"}'),
('drafts-pro','drafts','Drafts Pro','monthly',2.99,true,'Advanced actions, workspaces, themes','{"Advanced actions","Workspaces","Scripting","Themes"}'),
('obsidian-free','obsidian','Obsidian Free','free',0,false,'Local vault only','{"Unlimited local notes","Plugins","Community themes"}'),
('obsidian-sync','obsidian','Obsidian Sync','monthly',10,true,'End-to-end encrypted sync','{"E2E sync","1 year version history","Unlimited devices"}'),
('readwise-reader-free','readwise-reader','Reader Free','free',0,false,'Basic read-it-later','{"Read later","Highlights"}'),
('readwise-reader-full','readwise-reader','Reader Full','monthly',7.99,true,'Full reader + Readwise sync','{"Read later","Highlights","Readwise sync","AI summaries"}'),
('craft-free','craft','Craft Free','free',0,false,'Core documents','{"Unlimited docs","Basic sharing"}'),
('craft-pro','craft','Craft Pro','monthly',5.99,true,'Advanced sharing, version history, AI','{"Advanced sharing","AI writing","Version history"}'),
('dropbox-plus','dropbox','Dropbox Plus','monthly',11.99,true,'2 TB storage + 180-day history','{"2 TB storage","180-day version history","Transfer up to 2 GB"}'),
('dropbox-professional','dropbox','Dropbox Professional','monthly',19.99,false,'3 TB + 180-day history','{"3 TB storage","eSign","Smart Sync"}'),
('google-one-basic','google-one','Google One Basic','monthly',2.99,true,'100 GB storage','{"100 GB storage","Google expert support"}'),
('google-one-standard','google-one','Google One Standard','monthly',4.99,false,'200 GB storage','{"200 GB storage","Family sharing"}'),
('google-one-premium','google-one','Google One Premium','monthly',12.99,false,'2 TB storage','{"2 TB storage","Google AI features","VPN"}'),
('canva-free','canva','Canva Free','free',0,false,'Basic design tools','{"250k+ templates","5 GB storage"}'),
('canva-pro','canva','Canva Pro','monthly',14.99,true,'Brand Kit, background remover, 1 TB storage','{"Brand Kit","Background remover","1 TB storage","Magic Resize"}'),
('pixelmator-pro-standard','pixelmator-pro','Pixelmator Pro','one_time',49.99,true,'One-time purchase','{"Full image editing","ML features","Metal GPU rendering"}'),
('linea-link-standard','linea-link','Linea Link','one_time',9.99,true,'One-time purchase','{"Infinite canvas","Apple Pencil","Export"}'),
('affinity-photo-standard','affinity-photo','Affinity Photo 2','one_time',19.99,true,'One-time purchase','{"RAW editing","Retouching","HDR merge"}'),
('affinity-designer-standard','affinity-designer','Affinity Designer 2','one_time',19.99,true,'One-time purchase','{"Vector + raster","Export persona","Symbol library"}'),
('facetune-free','facetune','Facetune Free','free',0,false,'Basic retouching','{"Skin smoothing","Basic tools"}'),
('facetune-pro','facetune','Facetune Pro','monthly',7.99,true,'All AI tools unlocked','{"Body reshape","Background","AI filters","Video editing"}'),
('adobe-lightroom-free','adobe-lightroom','Lightroom Free','free',0,false,'Limited edits and storage','{"7 GB cloud","Basic presets"}'),
('adobe-lightroom-premium','adobe-lightroom','Lightroom Premium','monthly',9.99,true,'Full AI editing + 1 TB cloud','{"AI masking","1 TB cloud","Premium presets","Lens blur"}'),
('vsco-free','vsco','VSCO Free','free',0,false,'Basic editing tools','{"10 presets","Basic editing"}'),
('vsco-pro','vsco','VSCO Membership','annual',29.99,true,'All presets, video, montage','{"200+ presets","Video editing","Montage","Print"}'),
('darkroom-free','darkroom','Darkroom Free','free',0,false,'Core photo editing','{"Non-destructive edits","Basic filters"}'),
('darkroom-plus','darkroom','Darkroom+','monthly',9.99,true,'All filters, presets, video','{"All filters","Presets","Video editing","Batch"}'),
('halide-standard','halide','Halide Mark II','annual',11.99,true,'Full RAW camera subscription','{"RAW capture","Neural RAW","Histogram","Focus peaking"}'),
('luma-ai-free','luma-ai','Luma Free','free',0,false,'Limited 3D captures','{"30 captures/month","Standard quality"}'),
('luma-ai-pro','luma-ai','Luma Pro','monthly',9.99,true,'Unlimited HD captures','{"Unlimited captures","HD quality","Priority processing"}'),
('capcut-free','capcut','CapCut Free','free',0,false,'Core video editor','{"Basic editing","Transitions","Music"}'),
('capcut-pro','capcut','CapCut Pro','monthly',9.99,true,'AI features + watermark removal','{"AI background","Remove watermark","Enhance AI","Text-to-video"}'),
('netflix-standard','netflix','Netflix Standard','monthly',15.49,true,'Full HD, 2 streams','{"Full HD 1080p","2 screens","Downloads"}'),
('netflix-standard-ads','netflix','Netflix Standard w/ Ads','monthly',7.99,false,'HD, ads, 2 streams','{"HD 1080p","2 screens","Ads","Limited downloads"}'),
('netflix-premium','netflix','Netflix Premium','monthly',22.99,false,'4K + HDR, 4 streams','{"4K Ultra HD + HDR","4 screens","Spatial audio","4 downloads"}'),
('youtube-premium-individual','youtube-premium','YouTube Premium','monthly',13.99,true,'Ad-free, offline, background play','{"Ad-free","Background play","Offline downloads","YouTube Music"}'),
('youtube-premium-family','youtube-premium','YouTube Premium Family','monthly',22.99,false,'Up to 5 family members','{"Up to 5 members","All individual features"}'),
('disney-plus-basic','disney-plus','Disney+ Basic','monthly',7.99,false,'HD, ads','{"Ad-supported","HD","2 concurrent streams"}'),
('disney-plus-premium','disney-plus','Disney+ Premium','monthly',13.99,true,'4K + no ads','{"4K UHD","No ads","Dolby Atmos","4 streams"}'),
('hbo-max-with-ads','hbo-max','Max (With Ads)','monthly',9.99,false,'HD, limited ads','{"HD","1080p","2 streams","Ads"}'),
('hbo-max-ad-free','hbo-max','Max (Ad-Free)','monthly',15.99,true,'Full HD ad-free','{"Ad-free","1080p","2 streams","30 downloads"}'),
('hbo-max-ultimate','hbo-max','Max Ultimate','monthly',19.99,false,'4K UHD, Dolby Atmos','{"4K UHD","Dolby Atmos","4 streams","100 downloads"}'),
('amazon-prime-monthly','amazon-prime','Amazon Prime','monthly',14.99,true,'Prime Video + shopping + music','{"Prime Video","Prime Music","Free shipping","Prime Reading"}'),
('apple-tv-individual','apple-tv','Apple TV+','monthly',9.99,true,'Apple Original series and films','{"4K HDR","Dolby Atmos","6 family members"}'),
('apple-arcade-individual','apple-arcade','Apple Arcade','monthly',6.99,true,'200+ premium games, no ads','{"200+ games","No ads or IAP","Family Sharing"}'),
('headspace-free','headspace','Headspace Free','free',0,false,'Limited meditations','{"Basics course","3 meditations"}'),
('headspace-plus','headspace','Headspace+','monthly',12.99,true,'Full library of meditations and sleep content','{"500+ meditations","Sleep content","Focus music","Live events"}'),
('calm-free','calm','Calm Free','free',0,false,'Limited content','{"7 Days of Calm","Limited sleep stories"}'),
('calm-premium','calm','Calm Premium','annual',69.99,true,'Full access to all content','{"200+ Sleep Stories","Daily Calm","Music","Masterclasses"}'),
('strava-free','strava','Strava Free','free',0,false,'Basic activity tracking','{"GPS tracking","Activity feed","Routes"}'),
('strava-subscribe','strava','Strava Subscriber','monthly',11.99,true,'Advanced analytics + training plans','{"Segments","Training plans","Heart rate analysis","Live Segments"}'),
('noom-standard','noom','Noom','monthly',59.99,true,'Psychology-based weight loss program','{"Calorie tracking","Coaching","Curriculum","Health goals"}'),
('peloton-app-one','peloton','Peloton App One','monthly',12.99,false,'3 classes/month','{"3 classes/month","All class types"}'),
('peloton-app-plus','peloton','Peloton App+','monthly',24,true,'Unlimited classes','{"Unlimited classes","All modalities","Leaderboard"}'),
('whoop-membership','whoop','WHOOP Membership','monthly',30,true,'Health and fitness tracker subscription (hardware included)','{"Continuous monitoring","Recovery score","Sleep coaching","Hardware included"}'),
('mymacros-free','mymacros','MyFitnessPal Free','free',0,false,'Basic calorie counting','{"Calorie tracking","Basic food database","Exercise logging"}'),
('mymacros-premium','mymacros','MyFitnessPal Premium','monthly',9.99,true,'Advanced macros, meal planning, full analysis','{"Macro tracking","Meal planning","API access","Advanced analysis"}'),
('lifesum-free','lifesum','Lifesum Free','free',0,false,'Basic food diary','{"Food diary","Water tracking"}'),
('lifesum-premium','lifesum','Lifesum Premium','monthly',5.99,true,'Meal plans, advanced goals, insights','{"Meal plans","Personalized diet","Advanced insights","Recipes"}'),
('duolingo-free','duolingo','Duolingo Free','free',0,false,'Core language learning with ads','{"All languages","Basic path","Hearts system"}'),
('duolingo-super','duolingo','Duolingo Super','monthly',8.99,true,'Unlimited hearts, offline, no ads','{"Unlimited hearts","Offline","No ads","Streak repair"}'),
('babbel-monthly','babbel','Babbel Monthly','monthly',14.95,false,'1 language, monthly','{"1 language","All lessons","Offline"}'),
('babbel-annual','babbel','Babbel Annual','annual',83.4,true,'All languages for 1 year','{"All languages","Speech recognition","Live classes"}'),
('masterclass-individual','masterclass','MasterClass Individual','annual',120,false,'1 device, 1 account','{"All instructors","Offline downloads","1 account"}'),
('masterclass-duo','masterclass','MasterClass Duo','annual',150,true,'2 accounts, all classes','{"2 accounts","All instructors","Offline"}'),
('skillshare-membership','skillshare','Skillshare Membership','monthly',16.99,true,'Unlimited access to all classes','{"Unlimited classes","Offline viewing","Projects","Community"}'),
('coursera-plus','coursera','Coursera Plus','monthly',59,true,'Unlimited access to 7,000+ courses','{"7,000+ courses","Certificates","Specializations","Professional certificates"}'),
('robinhood-free','robinhood','Robinhood Free','free',0,false,'Basic investing','{"Commission-free trading","Stocks & ETFs","Crypto"}'),
('robinhood-gold','robinhood','Robinhood Gold','monthly',5,true,'Margin investing + research','{"Margin investing","Morningstar research","3% IRA match","5% interest"}'),
('coinbase-free','coinbase','Coinbase Free','free',0,false,'Basic crypto trading','{"Buy/sell crypto","Coinbase Wallet"}'),
('coinbase-advanced','coinbase','Coinbase Advanced','monthly',29.99,true,'Advanced trading + lower fees','{"Advanced charts","Volume discounts","Priority support"}'),
('ynab-annual','ynab','YNAB','annual',109,true,'Zero-based budgeting app','{"Goal tracking","Bank sync","Reports","Debt management"}'),
('personal-capital-free','personal-capital','Empower Free','free',0,true,'Free financial dashboard','{"Net worth","Investment tracking","Budgeting","Fee analyzer"}'),
('ivory-tip-jar','ivory','Ivory (Tip Jar)','monthly',1.99,true,'Optional tip jar subscription for Mastodon client','{"Full app features","Support development","Exclusive icons"}'),
('discord-free','discord','Discord Free','free',0,false,'Core messaging and voice','{"Voice/video","Servers","Basic emojis"}'),
('discord-nitro','discord','Discord Nitro','monthly',9.99,true,'Custom emojis, server boosts, HD video','{"Custom emojis","2 server boosts","HD video","100 MB uploads","Animated avatar"}'),
('telegram-premium-sub','telegram-premium','Telegram Premium','monthly',4.99,true,'No limits, exclusive features','{"No limits on media","Voice-to-text","4GB file uploads","Premium stickers","Faster downloads"}'),
('1password-individual','1password','1Password Individual','monthly',3.99,true,'Secure password manager for 1 person','{"Unlimited passwords","1 GB document storage","24/7 support","Watchtower"}'),
('1password-families','1password','1Password Families','monthly',6.95,false,'Up to 5 family members','{"5 members","Family vault sharing","Guest accounts"}'),
('nordvpn-standard','nordvpn','NordVPN Standard','monthly',12.99,true,'VPN + malware protection','{"VPN","Threat Protection","6 devices"}'),
('nordvpn-plus','nordvpn','NordVPN Plus','monthly',14.99,false,'VPN + password manager + data breach scanner','{"VPN","Password Manager","Data Breach Scanner"}'),
('expressvpn-standard','expressvpn','ExpressVPN','monthly',12.95,true,'Fast, secure VPN','{"VPN","8 devices","24/7 support","Network Lock"}'),
('tripit-free','tripit','TripIt Free','free',0,false,'Basic itinerary organiser','{"Master itinerary","Travel maps"}'),
('tripit-pro','tripit','TripIt Pro','annual',49.99,true,'Real-time alerts, seat tracking, loyalty management','{"Real-time alerts","Seat tracking","Points tracker","Flight refund"}'),
('proxyman-standard','proxyman','Proxyman','one_time',49.99,true,'One-time purchase (or subscription for updates)','{"HTTP/HTTPS debug","SSL pinning bypass","Scripting","Map local"}'),
('working-copy-standard','working-copy','Working Copy','one_time',19.99,true,'One-time unlock','{"Full Git client","Push/pull","SSH","Merge"}'),
('textsoap-standard','textsoap','Toolbox for Word','one_time',9.99,true,'One-time purchase','{"Word templates","Tools"}'),
('roblox-premium-450','roblox','Roblox Premium 450','monthly',4.99,false,'450 Robux/month + 10% bonus','{"450 Robux/month","10% bonus Robux","Trading"}'),
('roblox-premium-1000','roblox','Roblox Premium 1000','monthly',9.99,true,'1,000 Robux/month','{"1,000 Robux/month","10% bonus","Trading"}'),
('roblox-premium-2200','roblox','Roblox Premium 2200','monthly',19.99,false,'2,200 Robux/month','{"2,200 Robux/month","10% bonus","Trading"}'),
('kindle-unlimited','kindle','Kindle Unlimited','monthly',11.99,true,'Unlimited access to over 4 million titles','{"4M+ titles","Audiobooks","Magazines","Borrow 10 at a time"}'),
('audible-plus','audible','Audible Plus','monthly',7.95,false,'Unlimited Plus Catalogue listening','{"Plus Catalogue","Unlimited listening"}'),
('audible-premium','audible','Audible Premium','monthly',14.95,true,'1 credit/month + Plus Catalogue','{"1 credit/month","Plus Catalogue","30% off extras"}'),
('scribd-standard','scribd','Scribd','monthly',11.99,true,'Unlimited books, audiobooks, magazines, documents','{"Books","Audiobooks","Sheet music","Magazines","Documents"}'),
('shopify-basic','shopify','Shopify Basic','monthly',29,false,'For solo entrepreneurs','{"Online store","2 staff accounts","4 locations"}'),
('shopify-standard','shopify','Shopify','monthly',79,true,'For growing businesses','{"5 staff accounts","5 locations","Lower transaction fees"}'),
('shopify-advanced','shopify','Shopify Advanced','monthly',299,false,'For scaling','{"15 staff accounts","Advanced analytics","Custom reports"}'),
('day-one-free','day-one','Day One Free','free',0,false,'Single journal','{"1 journal","Basic entries"}'),
('day-one-premium','day-one','Day One Premium','monthly',4.99,true,'Unlimited journals, templates, end-to-end encryption','{"Unlimited journals","E2E encryption","Templates","IFTTT integration"}'),
('procreate-standard','procreate','Procreate','one_time',12.99,true,'One-time purchase','{"Full game"}'),
('minecraft-standard','minecraft','Minecraft','one_time',6.99,true,'One-time purchase','{"Full game"}'),
('monument-valley-standard','monument-valley','Monument Valley','one_time',3.99,true,'One-time purchase','{"Full game"}'),
('alto-odyssey-standard','alto-odyssey','Alto''s Odyssey','one_time',4.99,true,'One-time purchase','{"Full game"}'),
('bloons-td6-standard','bloons-td6','Bloons TD 6','one_time',4.99,true,'One-time purchase','{"Full game"}'),
('google-maps-free','google-maps','Google Maps Free','free',0,true,'Free app','{"Core features"}'),
('waze-free','waze','Waze Free','free',0,true,'Free app','{"Core features"}'),
('airbnb-free','airbnb','Airbnb Free','free',0,true,'Free app','{"Core features"}')
on conflict (id) do update set
  name=excluded.name, billing_period=excluded.billing_period,
  base_price_usd=excluded.base_price_usd, is_default=excluded.is_default,
  description=excluded.description, features=excluded.features,
  updated_at=now();

-- Backfill current_prices: set plan_id = default plan for each app
update current_prices cp
set plan_id = p.id
from plans p
where p.app_id = cp.app_id
  and p.is_default = true
  and cp.plan_id is null;
